config/routes.rb
Projet::Application.routes.draw do
  resources :users

  resources :devices

  resources :connections

  get "home/index"

  
  root "home#index"
  
  post 'devices/:id/connect' => 'devices#connect'
  patch 'devices/:id/turn' => 'devices#turn'
  patch 'devices/:id/turn2' => 'devices#turn2', :as => 'turn2'
  post 'devices/:id/add_user' => 'devices#add_user'
  put 'devices/:id/update' => 'devices#update'
  patch 'devices/:id/update' => 'devices#update', :as => 'update_device'

  

end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :user
	belongs_to :device

	validates :user_id, :device_id, presence: true
end

app/models/device.rb
class Device < ActiveRecord::Base
	has_many :connections
	has_many :users, through: :connections

	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :connections
	has_many :devices, through: :connections

	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
    # On ajoute la méthode connect dans la liste des méthodes où on set le connection au début
  before_action :set_connection, only: [:show, :edit, :update, :destroy]

  # On saute une etape de securite si on appelle connect en JSON
  skip_before_action :verify_authenticity_token, only: [:connect]

  # GET /connections
  # GET /connections.json
  def index
    @connections = Connection.all(:order => 'id ASC')
  end

  # GET /connections/1
  # GET /connections/1.json
  def show
  end

  # GET /connections/new
  def new
    @connection = Connection.new
  end

  # GET /connection/1/edit
  def edit
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(connection_params)

    respond_to do |format|
      if @connection.save
        format.html { redirect_to @connection, notice: 'Connection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @connection }
      else
        format.html { render action: 'new' }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1
  # PATCH/PUT /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        format.html { redirect_to @connection, notice: 'Connection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to connections_url }
      format.json { head :no_content }
    end
  end

  def set_connection
    @connection = Connection.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_params
      params.require(:connection).permit(:user_id, :device_id)
    end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
    # On ajoute la méthode connect dans la liste des méthodes où on set le device au début
  before_action :set_device, only: [:show, :edit, :update, :destroy, :add_user, :turn, :turn2]

  # On saute une etape de securite si on appelle connect en JSON
  skip_before_action :verify_authenticity_token, only: [:connect, :add_user, :turn, :update, :turn2]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all(:order => 'id ASC')
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  # POST /devices/1/connect.json
  def connect
    # On crée un nouvel objet connection à partir des paramètres reçus
    @connection = Connection.new(connection_params)
    # On précise l'idée du Device est celle dans les paramètres de l'URL
    # Sinon on modifie connection_params pour rajouter device_id
    @connection.device_id = params[:id]

    respond_to do |format|
      if @connection.save
        format.json
      else
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

    # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def turn
    respond_to do |format|
      if @device.update(device_params)
        format.json
      else
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def turn2
    @device.update_attribute(:status, !@device.status)

    if @device.status
         flash[:notice] = "Device has been turned on!"
      else
         flash[:notice] = "Device has been turned off!"
    end

    redirect_to :back
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :status)
    end

    # def add_user_params
    #   params.require(:device).permit(:user_id)
    # end

    def connection_params
      params.require(:connect).permit(:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all(:order => 'id ASC')
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/connections/_form.html.erb
<%= form_for(@connection) do |f| %>
  <% if @connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% @connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.text_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connections/edit.html.erb
<h1>Editing connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

app/views/connections/index.html.erb
<h1>Listing connections</h1>

<table>
  <thead>
    <tr>
		<th>Connection ID</th>
	  <th>User_name</th>
      <th>User_id</th>
      <th>Device_id</th>
	  <th>Device_name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @connections.each do |connection| %>
      <tr>
		<td><%= connection.id %></td>
		<td><%= User.find(connection.user_id).name %></td>
		<td><%= connection.user_id %></td>
		<td><%= connection.device_id %></td>
		<td><%= Device.find(connection.device_id).name %></td>
        <td><%= link_to 'Show', connection %></td>
        <td><%= link_to 'Edit', edit_connection_path(connection) %></td>
        <td><%= link_to 'Destroy', connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Connection', new_connection_path %>

app/views/connections/new.html.erb
<h1>New connection</h1>

<%= render 'form' %>

<%= link_to 'Back', connections_path %>

app/views/connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User id:</strong>
  <%= @connection.user_id %>
</p>

<p>
  <strong>Device id:</strong>
  <%= @connection.device_id %>
</p>

<%= link_to 'Edit', edit_connection_path(@connection) %> |
<%= link_to 'Back', connections_path %>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/index.html.erb
<br/>
<br/>
<br/>
<h1>Listing devices</h1>

<table>
  <thead>
	<tr>
	<th>ID</th>
      <th>Name</th>
      <th>Status</th>
      <th></th>
      <th></th>
	  <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
	  <td><%= device.id %></td>
        <td><%= device.name %></td>
        <td><%= device.status %></td>
	<!--	<td><%=link_to "ON/OFF", device_path(device), data: { params: { device: { status: !device.status} }.to_param }, :method => 'PATCH'%></td> -->
	<!--	<td><%=link_to "ON/OFF2", update_device_path(device), data: { params: { id: device.id, device: { status: !device.status, name: device.name} }.to_param }, :method => 'PATCH'%></td> -->
		<td><%=link_to "ON/OFF", turn2_path(device), :method => 'PATCH' %></td>
		<td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
<br/>
<br/>
<p>
  <strong>Name:</strong>
  <%= @device.name %>
  
  <strong>Number of users:</strong>
  <%= @device.connections.count %>
</p>

<p>
  <strong>Status:</strong>
  <%= @device.status %>
</p>

<h1>Listing users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User_id</th>
	  <th></th>
      <th></th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @device.connections.each do |connection| %>
      <tr>
	    <td><%= User.find(connection.user_id).name %></td>
		<td><%= connection.user_id %></td>
		<td><%= link_to 'Show User', user_path(connection.user_id) %></td>
        <td><%= link_to 'Edit User', edit_user_path(connection.user_id) %></td>
        <td><%= link_to 'Disconnect User', connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/home/index.html.erb
<br/>
<h1>Home#index</h1>
<h2>DomotiX est enfin sur Heroku !</h2>
<p><%= link_to 'Users', users_path %></p>
<p><%= link_to 'Devices', devices_path %></p>
<p><%= link_to 'Connections', connections_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Projet" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

<!--     <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Projet</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div> -->


    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Users", users_path  %></li>
                <li><%= link_to "Devices", devices_path  %></li>
                <li><%= link_to "Connections", connections_path  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; DomotiX 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <thead>
    <tr>
		<th>ID</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
	  <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
<br/>
<br/>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
  
  <strong>Devices number:</strong>
  <%= @user.connections.count %>
</p>

<h1>Listing devices</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Device_id</th>
      <th>Status</th>
      <th></th>
	  <th></th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user.connections.each do |connection| %>
      <tr>
	    <td><%= Device.find(connection.device_id).name %></td>
		<td><%= connection.device_id %></td>
		<td><%= Device.find(connection.device_id).status %></td>
		<td><%=link_to "ON/OFF", turn2_path(Device.find(connection.device_id)), :method => 'PATCH' %>
		<td><%= link_to 'Show Device', device_path(connection.device_id) %></td>
        <td><%= link_to 'Edit Device', edit_device_path(connection.device_id) %></td>
        <td><%= link_to 'Disconnect Device', connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>